# See AWS Build Specification Reference @ https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
    install:
        commands:
            - echo Entered the install phase...
            - npm install
    build:
        commands:
            - echo Entered the build phase...
            - echo Building ravenjs library + components...
            - npm run build
    post_build:
        commands:
            - echo Entered the post_build phase...
            - echo Packing the build...
            - npm pack
            - echo Build completed on `date`
artifacts:
    files:
        - ravenjs-1.0.0.tgz
